# Generated by Django 6.0.7 on 2026-09-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único na URL (ex: dermato, odonto)",
                        unique=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "duracao_slot_minutos",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Duração de cada consulta em minutos (ex: 20 para dermato, 40 para odonto)",
                    ),
                ),
                ("hora_abertura", models.TimeField(default="08:00")),
                ("hora_fechamento", models.TimeField(default="18:00")),
                (
                    "dias_semana",
                    models.CharField(
                        default="0,1,2,3,4",
                        help_text="Dias de funcionamento (0=Segunda, 4=Sexta, 5=Sábado, 6=Domingo)",
                        max_length=50,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Clínica",
                "verbose_name_plural": "Clínicas",
                "ordering": ["nome"],
            },
        ),
    ]
