# Generated by Django 6.0.7 on 2026-07-25 22:59

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[pacientes.validators.validar_cpf],
            ),
        ),
    ]
