# Generated by Django 6.0.7 on 2026-09-30 01:48

import django.db.models.deletion
import pacientes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "__first__"),
        ("pacientes", "0002_alter_paciente_cpf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="clinica",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica onde o paciente foi cadastrado",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacientes",
                to="clinicas.clinica",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Conta de login do paciente para acompanhar agendamentos",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_paciente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(
                max_length=14, validators=[pacientes.validators.validar_cpf]
            ),
        ),
    ]
