# Generated by Django 6.0.7 on 2026-07-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(default="mercadopago", max_length=30)),
                ("transacao_id", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="pendente", max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="agendamentos.agendamento",
                    ),
                ),
            ],
        ),
    ]
