# Generated by Django 6.0.7 on 2026-09-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "__first__"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="clinica",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica associada (vazio para administradores com acesso geral)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="clinicas.clinica",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador Geral"),
                    ("recepcao", "Recepção"),
                    ("profissional", "Médico / Dentista / Especialista"),
                    ("paciente", "Paciente"),
                ],
                default="recepcao",
                max_length=20,
            ),
        ),
    ]
