# Generated by Django 6.0.7 on 2026-07-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                            ("realizado", "Realizado"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[
                            ("nao_aplicavel", "Não aplicável"),
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                        ],
                        default="nao_aplicavel",
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
    ]
