# Generated by Django 6.0.7 on 2026-09-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("clinicas", "__first__"),
        ("pacientes", "0002_alter_paciente_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendamento",
            options={
                "ordering": ["data_hora"],
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.AddField(
            model_name="agendamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="clinica",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica do agendamento",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="clinicas.clinica",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="duracao_minutos",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="pacientes.paciente",
            ),
        ),
    ]
